import json, markdown, os, re, threading
from strands import Agent, tool
from strands.agent.agent_result import AgentResult
from strands.models.openai import OpenAIModel

import config
from src import app_logger
from src.agents.agent_tools import (
    canonical_brand_models, query_knowledge_async, web_search, folder_integrity
)

_callback_handler = None
_download_q = None  # will be set before each agent call

model = OpenAIModel(
    model_id=config.llm_config['model'],
    client_args={
        "api_key": config.llm_config['api_key'],
        "base_url": config.llm_config['base_url']
    }
)

def generate_html(file_name: str, content: AgentResult) -> str:
        """Generate a HTL from a markdown file and make it available for download.
            This tool can be used in parallel with the write_file tool.
        Args:
            file_name (str): The filename of the html file.
            content (str): The markdown content generated by the answer_agent.
        Returns:
            str: The path to the generated HTML file.
        """
        os.makedirs(config.agent['html_output'], exist_ok=True)
        output_path = os.path.join(config.agent['html_output'], file_name)

        html_content = markdown.markdown(str(content), extensions=["tables", "fenced_code"])
        
        html = f"""<!DOCTYPE html>
            <html lang="es">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <style>
                    body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; max-width: 900px; }}
                    h1, h2, h3 {{ color: #333; }}
                    code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: Courier; }}
                    pre {{ background: #f4f4f4; padding: 10px; border-radius: 5px; overflow-x: auto; }}
                    table {{ border-collapse: collapse; width: 100%; }}
                    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                    th {{ background: #f2f2f2; }}
                    blockquote {{ border-left: 4px solid #ddd; margin: 0; padding-left: 16px; color: #666; }}
                </style>
            </head>
            <body>
            {html_content}
            </body>
            </html>"""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        if _download_q:
            _download_q.put(output_path)
        return output_path

@tool
def brand_model_agent(query: str) -> AgentResult:
    """Agent to extract the brand and model from the user's question.
    Args:
        query (str): The user's question or query that needs to be answered based on the motorcycle manuals.
    Returns:
        str: The best scored"brand-model" key from the dictionary coming from the canonical_brand_models tool.
    """
    agent = Agent(
        model=model,
        tools=[canonical_brand_models, web_search],
        system_prompt=config.prompts['BRAND_MODEL_PROMPT'].format(score=config.agent['canonical_brand_score'])
    )
    return agent(f"Extract the brand and model from the user's question: '{query}'")

@tool
def query_versioning_agent(query: str) -> AgentResult:
    """Agent to make query versions in clear-technical way to perform vectorial search.
    Args:
        query (str): The user's question or query that needs to be answered.
    Returns:
        str: The user query versions in a list wrote in english.
    """
    app_logger.info("Trying to make query versions in clear-technical way to prepare vectorial search")
    agent = Agent(
        model=model,
        system_prompt=config.prompts['REWRITE_PROMPT'].format(query_copies=config.agent['query_copies'])
    )
    versions =  agent(f"Make versions of the user's question excluding the motorcycle brand-model: '{query}'")
    app_logger.info(f"Query versions: {versions}")
    return versions

@tool
def query_knowledge_agent(queries: list[str], canonical_brand_model: str) -> AgentResult:
    """Agent to querying the knowledge and structure solid-technical knowledge to be consumed by the orchestrator.
    Args:
        queries (list[str]): The rewritten query versions coming from query_versioning_agent in a list.
        canonical_brand_model (str): The best fit of possible canonical brand and model combinations coming from
            brand_model_agent.
    Returns:
        path (str): The path to the enriched chunks in json format.
    """
    app_logger.info("INSIDE query_knowledge_agent")
    agent = Agent(
        model=model,
        tools=[query_knowledge_async],
        system_prompt=config.prompts['KNOWLEDGE_QUERY_PROMPT'].format(query_copies=config.agent['query_copies']),
    )
    return agent(f"Query the knowledge database searching for question related chunks. The brand-model is '{canonical_brand_model}'. The queries are '{queries}'")

@tool
def answer_agent(chunks_path: str, user_question: str) -> str:
    """Agent to answer the user's question with a high-rich-technical markdown content.
    Args:
        chunks_path (str): The path to the enriched chunks generated in query_knowledge_agent.
        user_question (str): The user's question or query that needs to be answered.
    Returns:
        Successfully answered the user's question with a high-rich-technical markdown content.
    """

    # ... generate_html definition ...

    app_logger.info("Answering the user's question")
    with open(chunks_path, mode="r", encoding="utf-8") as f:
        enriched_chunks = json.loads(f.read())

    result = {}

    def create_and_run():
        # agent created in separate thread — outside Strands execution context
        agent = Agent(
            model=model,
            tools=[],
            system_prompt=config.prompts['ANSWER_PROMPT'].format(language=config.agent['answer_language']),
            callback_handler=_callback_handler
        )
        if len(enriched_chunks):
            result["content"] = agent(
                f"Answer the user's question '{user_question}' with a high-rich-technical markdown content. "
                f"Base your response on these enriched chunks: '{enriched_chunks}'"
                "Don't limit your answer to the user question: provide more related information contained in the chunks."
            )
        else:
            result["content"] = agent(
                "There's no chunks to answer the user's question. Answer the question with a clarification message."
                "Follow the instructions"
                "a. You should misunderstood the brand-model, ask user to be more specific. Providing canonical brand-model."
                "b. You should misunderstood the user's question, ask user to be more specific and provide the query versions"
                "you tried."
            )

    thread = threading.Thread(target=create_and_run)
    thread.start()
    thread.join()
    if len(enriched_chunks):
        filename = re.sub(r'\W+', '_', user_question)+'.html'
        output_path = generate_html(filename, result["content"])
        return f'User query was successfully answered and placed in {output_path}'
    else:
        return 'User query was successfully answered but no chunks were found. Close the interaction.'

@tool
def export_results_agent(markdown_content: str) -> AgentResult:
    """Agent to write the markdown content to a markdown and html files.
    Args:
        markdown_content (str): The answer in high-rich-technical markdown content
            coming from answer_agent.
    Returns:
        file_path (str): The path of the html file. This is the path to the HTML file, not the markdown file.
    """
    app_logger.info("Writing the markdown content to a markdown file")
    agent = Agent(
        model=model,
        system_prompt=config.prompts['EXPORT_RESULTS_PROMPT'].format(
            knowledge_output=config.agent['knowledge_output'],
            html_output=config.agent['html_output']
        )
    )
    return agent(f"Write the markdown content to a markdown and html files. The markdown content is '{markdown_content}'")