import markdown, os
from typing import Any

import config
from src.commons import get_brands

brands = get_brands()

_download_q = None  # will be set before each agent call


def get_available_brands_models() -> str:
    """Get a list of available brands and models.
    Returns:
        str: A list of available brands and models.
    """
    def brand_formatting(brand_models: str) -> str:
        """Format a Brand-Model string to be humanly readable and friendly.
        Args:
            brand_models (str): The brand-model string to be formatted.
        Returns:
            str: The formatted brand-model string.
        """
        brand = brand_models.split('-')[0].strip()
        if len(brand)<=4:
            brand = brand_models.split('-')[0].strip().upper()
        else:
            brand = brand_models.split('-')[0].strip().capitalize()
        model = '-'.join(brand_models.split('-')[1:]).strip().upper()
        return f"{brand} - {model}"
    brands_values = list({dict_['brand'] for dict_ in brands.values()})
    brands_models = list({brand_formatting(dict_['motorcycle']) for dict_ in brands.values()})
    brands_models = sorted(brands_models)
    formatted_string = "\n\n## Las motos disponibles son:"
    for brand in brands_values:
        formatted_string += f"\n\n### {brand}\n"
        brand = list(filter(lambda x: brand.lower() in x.lower(),brands_models))
        formatted_string += '\n- '+'\n- '.join(brand)
    return formatted_string

def generate_html(file_name: str, content: Any) -> str:
        """Generate a HTL from a markdown file and make it available for download.
            This tool can be used in parallel with the write_file tool.
        Args:
            file_name (str): The filename of the html file.
            content (str): The markdown content generated by the answer_agent.
        Returns:
            str: The path to the generated HTML file.
        """
        os.makedirs(config.agent['html_output'], exist_ok=True)
        output_path = os.path.join(config.agent['html_output'], file_name)

        html_content = markdown.markdown(str(content), extensions=["tables", "fenced_code"])
        
        html = f"""<!DOCTYPE html>
            <html lang="es">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <style>
                    body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; max-width: 900px; }}
                    h1, h2, h3 {{ color: #333; }}
                    code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-family: Courier; }}
                    pre {{ background: #f4f4f4; padding: 10px; border-radius: 5px; overflow-x: auto; }}
                    table {{ border-collapse: collapse; width: 100%; }}
                    th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                    th {{ background: #f2f2f2; }}
                    blockquote {{ border-left: 4px solid #ddd; margin: 0; padding-left: 16px; color: #666; }}
                </style>
            </head>
            <body>
            {html_content}
            </body>
            </html>"""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        if _download_q:
            _download_q.put(output_path)
        return output_path